### ISSUE TITLE
http commands

### ISSUE THREAD

**Issue by mellotanica** [chadparry/kodi-plugin.program.remote.control.browser#2]
this is more a request than an issue, but would it be too much difficult to respond to http web server commands as well?

i don't have any ir receiver nor a spare remote but i use an android remote to control kodi and i would love to be able to use the remote app and kodi to browse netflix but it seems your plugin is only letting through lirc input, not the regular one

**Comment by chadparry** [comment]
I think that's a great idea. I'll look into whether it's technically feasible. I'm not sure whether the the Kodi web server is extensible for add-ons. It may be that there would have to be changes to the Kodi core to allow an add-on to see events from an Android remote.

**Comment by mellotanica** [comment]
i have really limited knowledge about kodi plugins api and it's also outdated knowledge, so i don't know if what i thought is feasible or not. i was wandering if it could be possible to grab kodi control input in some way and use it to control the browser or to simulate lirc input in some way, avoiding the necessity to deal with different input sources

**Comment by chadparry** [comment]
I'm still looking into this kind of extension. As a workaround, I recommend you try an app such as [DroidMote](http://www.videomap.it/) (for Android) or [HippoRemote](http://hipporemote.com/lite) (for iOS). I haven't tried them, but they look like they will do what you need. Once you fire up the browser from your Kodi remote control, you could switch to one of those apps for controlling the mouse.

**Comment by chadparry** [comment]
I didn't get any response on the [Kodi forum](http://forum.kodi.tv/showthread.php?tid=304695). This isn't going to be possible for an add-on. Please report back if you have any luck with those other phone apps, though.

**Comment by mellotanica** [comment]
right now i'm using [KDEConnect](https://community.kde.org/KDEConnect) but it's a rather specific app that works only with linux and KDE desktop environment. i think your suggestion is still much more applicable to the general case. thank you anyway!
