### ISSUE TITLE
Plugin.py does not have logging enabled

### ISSUE THREAD

**Issue by andrewsimpsonnz** [chadparry/kodi-plugin.program.remote.control.browser#4]
Plugin.py does not have logging enabled.  This leads to a crash on line 181 on my system (Ubuntu 18.04) when loading the browser.
Adding logging similar to browser.py solves the problem.  Patch for plugin.py is attached.
[logger-patch.txt](https://github.com/chadparry/kodi-plugin.program.remote.control.browser/files/2729232/logger-patch.txt)

**Comment by chadparry** [comment]
That's definitely going to be a problem for any environments without Pulse Python libraries installed. And thanks a ton for the patch! I'll change that to use Kodi's supported logging. I'll also add detection for the Python libraries, so people can see what they are missing on the configuration page.

**Comment by chadparry** [comment]
The crash is now fixed (https://github.com/chadparry/kodi-plugin.program.remote.control.browser/commit/ed54bc9c96afe376ded5e0fcc667f7a060336ae1#diff-9d636221cd8f9439c20761d1c1d30cf9) and I've released version 1.4.0. This is available now on my personal repository. I'll start the PR to update the official repository.
